apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-techtrends-prod
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: project/helm/techtrends
    repoURL: 'https://github.com/bigfleet/nd064_course_1.git'
    targetRevision: main
    helm:
      valueFiles:
        - values-prod.yaml
  project: default
  syncPolicy:
    automated: null